spring:
  web:
    resources:
      add-mappings: false

  application:
    name: msyql_example

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-containergi:3306/post_db?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: yhj
    password: yhj

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    root: debug

jwt:
  secret: ThisIsTestKeyThisIsTestKeyThisIsTestKeyThisIsTestKeyThisIsTestKeyThisIsTestKey